# Base url
baseurl: 
# Site url
url: http://gayanvirajith.github.io
# Site name
name: Gayan Virajith
# Markdown vendors
markdown: redcarpet
# Python plugin for syntax high lighting
pygments: true
# Paginate limit
paginate: 10 # Pagination based on number of post
# Path to paginate
paginate_path: "posts/page:num"
