# Base URL
baseurl:  # the subpath of your site, e.g. /blog/

# Site live URL
url: http://localhost:4000 # the base hostname & protocol for your site

# Go theme based configuration. Please change accordingly.
go:
  title: Gayan Virajith
  tag_line: 

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 