# Go Jekyll theme general configurations

# Base URL
baseurl: / # the subpath of your site, e.g. /blog/

# Site live URL
url: http://gayan.me # the base hostname & protocol for your site
# url: http://localhost:4000 # the base hostname & protocol for your site

# Go theme based configuration. Please change accordingly.
go:
  title: Gayan Virajith
  tag_line: 
  meta_description: > # this means to ignore newlines until "author:"
   Gayan Virajith, Web developer at Mearch ICT (template-factory.nl).
   I do Processwire CMS/CMF web development.
    
  # Author details
  author: 
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayan.me

  # Profile links, leave blank to ignore
  social: 
    github: gayanvirajith
    twitter: gayanvirajith
    facebook: gayanvirajith
    gplus: +GayanVirajith
    dribble: gayan
    pinterest: 

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-51832325-1
  google_webmaster_key: iGowBFvyZY0ukLqi04rYcC2EWhpQIUUtIbwsuHv2YS8

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

# Pagination config
paginate: 2

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed